name: Random Message to Slack

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Custom message'
        required: false

jobs:
  random_message_to_slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk
          pip install python-dotenv

      - name: Run script
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          echo ${{secrets.SLACK_TOKEN}} | sed 's/ //g'
          echo ${{secrets.CHANNEL_ID}} | sed 's/ //g'
